In [223]:
import numpy as np 
import pandas as pd


In [224]:
df=pd.read_csv("C:\\Users\\RABIN RESIN\\Desktop\\luminar\\development-journey\\mechine learning journey\\feature engineering\\lung_cancer\\survey lung cancer.csv")
df.shape

(309, 16)

In [225]:
df.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      M   69        1               2        2              1   
1      M   74        2               1        1              1   
2      F   59        1               1        1              2   
3      M   63        2               2        2              1   
4      F   63        1               2        1              1   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
0                    2                      2           2         YES  
1                    2                      2           2         YES  
2                    2                      1           2          NO  
3                    1                      2           2          NO  
4                    2                      1           1          NO

In [226]:
df.isnull().sum()

GENDER                   0
AGE                      0
SMOKING                  0
YELLOW_FINGERS           0
ANXIETY                  0
PEER_PRESSURE            0
CHRONIC DISEASE          0
FATIGUE                  0
ALLERGY                  0
WHEEZING                 0
ALCOHOL CONSUMING        0
COUGHING                 0
SHORTNESS OF BREATH      0
SWALLOWING DIFFICULTY    0
CHEST PAIN               0
LUNG_CANCER              0
dtype: int64

In [227]:
df.columns

Index(['GENDER', 'AGE', 'SMOKING', 'YELLOW_FINGERS', 'ANXIETY',
       'PEER_PRESSURE', 'CHRONIC DISEASE', 'FATIGUE ', 'ALLERGY ', 'WHEEZING',
       'ALCOHOL CONSUMING', 'COUGHING', 'SHORTNESS OF BREATH',
       'SWALLOWING DIFFICULTY', 'CHEST PAIN', 'LUNG_CANCER'],
      dtype='object')

In [228]:
X=df.iloc[:,:-1]
Y=df.iloc[:,-1]

In [229]:
X

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0        M   69        1               2        2              1   
1        M   74        2               1        1              1   
2        F   59        1               1        1              2   
3        M   63        2               2        2              1   
4        F   63        1               2        1              1   
..     ...  ...      ...             ...      ...            ...   
304      F   56        1               1        1              2   
305      M   70        2               1        1              1   
306      M   58        2               1        1              1   
307      M   67        2               1        2              1   
308      M   62        1               1        1              2   

     CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  \
0                  1         2         1         2                  2   
1                  2         2         2         1                  1   
2                  1         2         1         2                  1   
3                  1         1         1         1                  2   
4                  1         1         1         2                  1   
..               ...       ...       ...       ...                ...   
304                2         2         1         1                  2   
305                1         2         2         2                  2   
306                1         1         2         2                  2   
307                1         2         2         1                  2   
308                1         2         2         2                  2   

     COUGHING  SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  
0           2                    2                      2           2  
1           1                    2                      2           2  
2           2                    2                      1           2  
3           1                    1                      2           2  
4           2                    2                      1           1  
..        ...                  ...                    ...         ...  
304         2                    2                      2           1  
305         2                    2                      1           2  
306         2                    1                      1           2  
307         2                    2                      1           2  
308         1                    1                      2           1  

[309 rows x 15 columns]

In [230]:
Y

0      YES
1      YES
2       NO
3       NO
4       NO
      ... 
304    YES
305    YES
306    YES
307    YES
308    YES
Name: LUNG_CANCER, Length: 309, dtype: object

handling missing values

In [231]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy="mean")
X.iloc[:,1:14]=imputer.fit_transform(X.iloc[:,1:14])
X

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0        M   69        1               2        2              1   
1        M   74        2               1        1              1   
2        F   59        1               1        1              2   
3        M   63        2               2        2              1   
4        F   63        1               2        1              1   
..     ...  ...      ...             ...      ...            ...   
304      F   56        1               1        1              2   
305      M   70        2               1        1              1   
306      M   58        2               1        1              1   
307      M   67        2               1        2              1   
308      M   62        1               1        1              2   

     CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  \
0                  1         2         1         2                  2   
1                  2         2         2         1                  1   
2                  1         2         1         2                  1   
3                  1         1         1         1                  2   
4                  1         1         1         2                  1   
..               ...       ...       ...       ...                ...   
304                2         2         1         1                  2   
305                1         2         2         2                  2   
306                1         1         2         2                  2   
307                1         2         2         1                  2   
308                1         2         2         2                  2   

     COUGHING  SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  
0           2                    2                      2           2  
1           1                    2                      2           2  
2           2                    2                      1           2  
3           1                    1                      2           2  
4           2                    2                      1           1  
..        ...                  ...                    ...         ...  
304         2                    2                      2           1  
305         2                    2                      1           2  
306         2                    1                      1           2  
307         2                    2                      1           2  
308         1                    1                      2           1  

[309 rows x 15 columns]

### encoding categorical value

In [232]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer([("enocoder",OneHotEncoder(),[0])],remainder="passthrough")
X=pd.DataFrame(ct.fit_transform(X))
X

0    1     2    3    4    5    6    7    8    9    10   11   12   13  \
0    0.0  1.0  69.0  1.0  2.0  2.0  1.0  1.0  2.0  1.0  2.0  2.0  2.0  2.0   
1    0.0  1.0  74.0  2.0  1.0  1.0  1.0  2.0  2.0  2.0  1.0  1.0  1.0  2.0   
2    1.0  0.0  59.0  1.0  1.0  1.0  2.0  1.0  2.0  1.0  2.0  1.0  2.0  2.0   
3    0.0  1.0  63.0  2.0  2.0  2.0  1.0  1.0  1.0  1.0  1.0  2.0  1.0  1.0   
4    1.0  0.0  63.0  1.0  2.0  1.0  1.0  1.0  1.0  1.0  2.0  1.0  2.0  2.0   
..   ...  ...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
304  1.0  0.0  56.0  1.0  1.0  1.0  2.0  2.0  2.0  1.0  1.0  2.0  2.0  2.0   
305  0.0  1.0  70.0  2.0  1.0  1.0  1.0  1.0  2.0  2.0  2.0  2.0  2.0  2.0   
306  0.0  1.0  58.0  2.0  1.0  1.0  1.0  1.0  1.0  2.0  2.0  2.0  2.0  1.0   
307  0.0  1.0  67.0  2.0  1.0  2.0  1.0  1.0  2.0  2.0  1.0  2.0  2.0  2.0   
308  0.0  1.0  62.0  1.0  1.0  1.0  2.0  1.0  2.0  2.0  2.0  2.0  1.0  1.0   

      14   15  
0    2.0  2.0  
1    2.0  2.0  
2    1.0  2.0  
3    2.0  2.0  
4    1.0  1.0  
..   ...  ...  
304  2.0  1.0  
305  1.0  2.0  
306  1.0  2.0  
307  1.0  2.0  
308  2.0  1.0  

[309 rows x 16 columns]

In [233]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

In [234]:
Y

array([1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

## split X and Y to train test

In [235]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.2,random_state=42)

In [236]:
xtrain

0    1     2    3    4    5    6    7    8    9    10   11   12   13  \
126  0.0  1.0  51.0  2.0  1.0  1.0  1.0  1.0  2.0  1.0  2.0  2.0  2.0  2.0   
109  0.0  1.0  53.0  1.0  1.0  1.0  1.0  2.0  2.0  2.0  1.0  2.0  1.0  2.0   
247  0.0  1.0  67.0  1.0  2.0  1.0  1.0  1.0  2.0  1.0  2.0  2.0  2.0  2.0   
234  0.0  1.0  77.0  1.0  2.0  1.0  2.0  1.0  2.0  2.0  2.0  2.0  2.0  1.0   
202  0.0  1.0  74.0  2.0  1.0  1.0  1.0  2.0  2.0  2.0  2.0  2.0  1.0  1.0   
..   ...  ...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
188  0.0  1.0  65.0  2.0  2.0  2.0  2.0  2.0  1.0  1.0  1.0  1.0  1.0  1.0   
71   1.0  0.0  66.0  2.0  2.0  2.0  2.0  1.0  2.0  1.0  2.0  1.0  2.0  2.0   
106  1.0  0.0  61.0  2.0  2.0  2.0  2.0  2.0  2.0  1.0  1.0  1.0  1.0  2.0   
270  1.0  0.0  70.0  2.0  1.0  1.0  1.0  1.0  2.0  1.0  1.0  1.0  1.0  2.0   
102  0.0  1.0  64.0  2.0  1.0  1.0  1.0  1.0  2.0  2.0  2.0  2.0  2.0  2.0   

      14   15  
126  1.0  2.0  
109  1.0  2.0  
247  1.0  1.0  
234  1.0  1.0  
202  2.0  2.0  
..   ...  ...  
188  1.0  1.0  
71   2.0  1.0  
106  2.0  1.0  
270  1.0  1.0  
102  1.0  2.0  

[247 rows x 16 columns]

## feature scaling

In [237]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
xtrain=scaler.fit_transform(xtrain)

In [238]:
xtrain

array([[-0.93338744,  0.93338744, -1.39514731, ...,  0.71787006,
        -0.86704847,  0.91830473],
       [-0.93338744,  0.93338744, -1.14705416, ...,  0.71787006,
        -0.86704847,  0.91830473],
       [-0.93338744,  0.93338744,  0.58959789, ...,  0.71787006,
        -0.86704847, -1.08896313],
       ...,
       [ 1.07136646, -1.07136646, -0.15468156, ...,  0.71787006,
         1.15333806, -1.08896313],
       [ 1.07136646, -1.07136646,  0.96173762, ...,  0.71787006,
        -0.86704847, -1.08896313],
       [-0.93338744,  0.93338744,  0.21745817, ...,  0.71787006,
        -0.86704847,  0.91830473]], shape=(247, 16))

In [239]:
xtest=scaler.fit_transform(xtest)

In [240]:
xtest

array([[ 0.96824584, -0.96824584, -0.39627636, -1.10194633,  0.69006556,
         0.84983659,  0.93743687, -1.21655251, -1.0667385 ,  0.74161985,
         0.79471941, -1.25830574,  0.87831007, -1.13855009,  0.76794765,
        -1.25830574],
       [-1.03279556,  1.03279556, -1.3367217 ,  0.90748521,  0.69006556,
         0.84983659,  0.93743687,  0.82199494, -1.0667385 ,  0.74161985,
        -1.25830574,  0.79471941, -1.13855009, -1.13855009,  0.76794765,
         0.79471941],
       [-1.03279556,  1.03279556,  1.01439164, -1.10194633, -1.44913767,
        -1.17669681, -1.0667385 ,  0.82199494, -1.0667385 ,  0.74161985,
        -1.25830574,  0.79471941,  0.87831007,  0.87831007,  0.76794765,
         0.79471941],
       [-1.03279556,  1.03279556,  0.66172464, -1.10194633,  0.69006556,
        -1.17669681,  0.93743687,  0.82199494,  0.93743687,  0.74161985,
         0.79471941,  0.79471941,  0.87831007, -1.13855009,  0.76794765,
         0.79471941],
       [-1.03279556,  1.03279556,  0

# selecting algorithm
where choosing k nearest algorithm

In [241]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=3)

In [242]:
y_pred=knn.predict(xtest)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [243]:
ytest

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [244]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest,y_pred)

0.9193548387096774